POST http://{{local}}/categorias/create
Content-Type: application/json

{
  "nombre": "Principal",
  "descripcion": "Platos principales"
}

###
GET http://{{local}}/categorias/get/2

###
PUT http://{{local}}/categorias/update
Content-Type: application/json

{
  "id": 3,
  "nombre": "Postres",
  "descripcion": "Postres"
}


###
DELETE http://{{local}}/categorias/delete/1

###
GET http://{{local}}/categorias/get
