POST http://{{local}}/productos/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGVsbGlkbyI6InBhbGV0IiwiZW1haWwiOiJwYWxldGdlcmFyZG9AZ21haWwuY29tIiwiZXhwIjoxNjEwODM5MDM1LCJmZWNoYU5hY2ltaWVudG8iOiIxOTgzLTAzLTEyVDIzOjE3OjExWiIsImlkIjoxLCJub21icmUiOiJIdWdvIEdlcmFyZG8ifQ.5pqhgZRt7wxK8bQGipt6ij-rZ2Mqdy4-wJIqyxsngJ8
{
  "nombre": "Cerveza",
  "descripcion": "Cerveza",
  "precio": 255.36
}

###
GET http://{{local}}/productos/get/9

###
PUT http://{{local}}/productos/update
Content-Type: application/json

{
  "id": 14,
  "nombre": "Cerveza update 14",
  "descripcion": "Cerveza",
  "precio": 255.36
}


###
DELETE http://{{local}}/productos/delete/15

###
GET http://{{local}}/productos/get
