POST http://{{local}}/productos/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGVsbGlkbyI6InBhbGV0IiwiZW1haWwiOiJwYWxldGdlcmFyZG9AZ21haWwuY29tIiwiZXhwIjoxNjEwODQxOTExLCJmZWNoYU5hY2ltaWVudG8iOiIxOTgzLTAzLTEyVDIzOjE3OjExWiIsImlkIjoxLCJub21icmUiOiJIdWdvIEdlcmFyZG8ifQ.ks-XkoLr3pPhRLDDtyfk0Ve4OiQR1MSGfgdmuZWVcPI
{
  "nombre": "Cerveza",
  "descripcion": "Cerveza",
  "precio": 255.36
}

###
GET http://{{local}}/productos/get/9

###
PUT http://{{local}}/productos/update
Content-Type: application/json

{
  "id": 14,
  "nombre": "Cerveza update 14",
  "descripcion": "Cerveza",
  "precio": 255.36
}


###
DELETE http://{{local}}/productos/delete/15

###
GET http://{{local}}/productos/get
